# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='revenue',
            field=models.IntegerField(default=0),
        ),
    ]
