# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mto', '0002_company_revenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='modl',
            field=models.CharField(default=1, max_length=15),
        ),
    ]
