# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mto', '0003_car_modl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='modl',
            field=models.CharField(default='', max_length=15),
        ),
    ]
